# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 09:41
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.get_black_list_path, verbose_name='\u6587\u4ef6')),
                ('size', models.BigIntegerField(default=0, verbose_name='\u5927\u5c0f')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u9ed1\u540d\u5355',
                'verbose_name_plural': '\u9ed1\u540d\u5355',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(default=core.models.gen_job_id, max_length=32, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u626b\u63cf\u4efb\u52a1', max_length=30, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('port', models.IntegerField(verbose_name='\u626b\u63cf\u7aef\u53e3')),
                ('bandwidth', models.IntegerField(default=100, verbose_name='\u5e26\u5bbd')),
                ('priority', models.IntegerField(choices=[(0, '\u4f4e'), (1, '\u4e2d'), (2, '\u9ad8'), (3, '\u6781\u9ad8')], default=1, verbose_name='\u4f18\u5148\u7ea7')),
                ('output_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8f93\u51fa\u6587\u4ef6')),
                ('log_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u65e5\u5fd7\u6587\u4ef6')),
                ('status', models.IntegerField(choices=[(0, '\u7b49\u5f85\u6267\u884c'), (1, '\u6b63\u5728\u6267\u884c'), (2, '\u6267\u884c\u5b8c\u6210'), (3, '\u6267\u884c\u9519\u8bef')], default=0, verbose_name='\u72b6\u6001')),
                ('progress', models.CharField(blank=True, max_length=3, null=True, verbose_name='\u6267\u884c\u8fdb\u5ea6')),
                ('left_time', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u5269\u4f59\u65f6\u95f4')),
                ('verbosity', models.IntegerField(default=3, verbose_name='\u65e5\u5fd7\u7ea7\u522b')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='\u542f\u52a8\u65f6\u95f4')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('hit_rate', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u547d\u4e2d\u7387')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('black_list_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BlackListFile', verbose_name='\u9ed1\u540d\u5355')),
            ],
            options={
                'verbose_name': '\u4efb\u52a1',
                'verbose_name_plural': '\u4efb\u52a1',
            },
        ),
        migrations.CreateModel(
            name='WhiteListFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.get_white_list_path, verbose_name='\u6587\u4ef6')),
                ('size', models.BigIntegerField(default=0, verbose_name='\u5927\u5c0f')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u767d\u540d\u5355',
                'verbose_name_plural': '\u767d\u540d\u5355',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='white_list_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.WhiteListFile', verbose_name='\u767d\u540d\u5355'),
        ),
    ]
