# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistfile',
            options={'verbose_name': '\u9ed1\u540d\u5355', 'verbose_name_plural': '\u9ed1\u540d\u5355'},
        ),
        migrations.AlterModelOptions(
            name='whitelistfile',
            options={'verbose_name': '\u767d\u540d\u5355', 'verbose_name_plural': '\u767d\u540d\u5355'},
        ),
        migrations.AlterField(
            model_name='job',
            name='black_list_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BlackListFile', verbose_name='\u9ed1\u540d\u5355'),
        ),
        migrations.AlterField(
            model_name='job',
            name='input_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.WhiteListFile', verbose_name='\u767d\u540d\u5355'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, '\u7b49\u5f85\u6267\u884c'), (1, '\u6b63\u5728\u6267\u884c'), (2, '\u6267\u884c\u5b8c\u6210'), (3, '\u6267\u884c\u9519\u8bef')], default=0, verbose_name='\u72b6\u6001'),
        ),
    ]
