# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u72b6\u6001\u6587\u4ef6'),
        ),
    ]
