# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_status_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bandwidth',
            field=models.IntegerField(default=1, verbose_name='\u5e26\u5bbd'),
        ),
        migrations.AlterField(
            model_name='job',
            name='verbosity',
            field=models.IntegerField(choices=[(0, 'FATAL'), (1, 'ERROR'), (2, 'WARN'), (3, 'INFO'), (4, 'DEBUG'), (5, 'TRACE')], default=3, verbose_name='\u65e5\u5fd7\u7ea7\u522b'),
        ),
    ]
