# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 03:24
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160704_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(default=core.models.gen_job_id, max_length=32, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
