# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160706_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='active_send_threads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='drop_avg_per_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='drop_last_one_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='pcap_drop_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='percent_complete',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='read_time',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='recv_success_avg_per_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='recv_success_last_one_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='recv_success_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='recv_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='recv_total_avg_per_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='recv_total_last_one_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='sendto_fail_avg_per_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='sendto_fail_last_one_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='sendto_fail_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='sent_avg_per_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='sent_last_one_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='sent_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='time_elapsed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='time_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
