# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160706_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pid',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='\u8fdb\u7a0b\u53f7'),
        ),
    ]
