# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_job_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pid',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u8fdb\u7a0b\u53f7'),
        ),
    ]
