# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160706_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='hit_rate',
        ),
        migrations.RemoveField(
            model_name='job',
            name='left_time',
        ),
        migrations.RemoveField(
            model_name='job',
            name='progress',
        ),
    ]
