# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160706_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.IntegerField()),
                ('status', models.IntegerField()),
                ('job_id', models.CharField(max_length=32)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='read_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, '\u7b49\u5f85\u6267\u884c'), (1, '\u6b63\u5728\u6267\u884c'), (2, '\u6267\u884c\u5b8c\u6210'), (3, '\u6267\u884c\u9519\u8bef'), (4, '\u6682\u505c')], default=0, verbose_name='\u72b6\u6001'),
        ),
    ]
