# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160706_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Command',
        ),
    ]
