# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistfile',
            name='name',
            field=models.CharField(default=1, max_length=30, verbose_name='\u540d\u79f0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitelistfile',
            name='name',
            field=models.CharField(default=1, max_length=30, verbose_name='\u540d\u79f0'),
            preserve_default=False,
        ),
    ]
