# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160707_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cmd', models.IntegerField(choices=[(0, 'PAUSE'), (1, 'CONTINUE'), (2, 'STOP')])),
                ('status', models.IntegerField(choices=[(0, 'WAIT'), (1, 'RUNNING'), (2, 'DONE'), (3, 'ERROR')])),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Job')),
            ],
        ),
    ]
