# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_command'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'verbose_name': '\u547d\u4ee4', 'verbose_name_plural': '\u547d\u4ee4'},
        ),
        migrations.AlterField(
            model_name='blacklistfile',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='command',
            name='cmd',
            field=models.IntegerField(choices=[(0, 'PAUSE'), (1, 'CONTINUE'), (2, 'STOP'), (3, 'CANCEL')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'WAIT'), (1, 'RUNNING'), (2, 'DONE'), (3, 'ERROR'), (4, 'PAUSE'), (5, 'CANCELED'), (6, 'STOPPED')], default=0, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='whitelistfile',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u540d\u79f0'),
        ),
    ]
