# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160707_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'RUNNING'), (2, 'DONE'), (3, 'ERROR')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'RUNNING'), (2, 'DONE'), (3, 'ERROR'), (4, 'PAUSE'), (5, 'CANCELED'), (6, 'STOPPED')], default=0, verbose_name='\u72b6\u6001'),
        ),
    ]
