# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160712_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='cmd',
            field=models.IntegerField(choices=[(0, 'PAUSE'), (1, 'CONTINUE'), (2, 'STOP'), (3, 'CANCEL')], default=0),
        ),
    ]
