# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160712_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='cmd',
            field=models.IntegerField(choices=[(0, 'PAUSE'), (1, 'CONTINUE'), (2, 'STOP')]),
        ),
        migrations.AlterField(
            model_name='command',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'DONE'), (2, 'ERROR')], default=0),
        ),
    ]
