# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20160712_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'RUNNING'), (2, 'DONE'), (3, 'ERROR'), (4, 'PAUSE'), (5, 'STOPPED'), (6, 'CANCELED')], default=0, verbose_name='\u72b6\u6001'),
        ),
    ]
