# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160713_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='subnets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u76ee\u6807\u5b50\u7f51'),
        ),
    ]
