# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_job_subnets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bandwidth',
            field=models.IntegerField(default=2, verbose_name='\u5e26\u5bbd'),
        ),
    ]
